spring:
  application:
    name: KotlinSpringTemplate
  datasource:
    url: jdbc:mysql://localhost:3306/mysqltutorialorg_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true